npm install request
npm install socket.io-client
npm install binaryjs
npm install tv4
npm install restify
npm install json-schema
npm install caterpillar
npm install dnode
npm install express
npm install gm
npm install inspect
npm install jade
npm install jsdom
npm install mc
npm install mongodb
npm install now
npm install websocket
npm install zmq
npm install jQuery
npm install xmlhttprequest
npm install mime
npm install portscanner
npm install ws

